<?php

namespace app\components;

class HelloWidget extends \yii\base\Widget
{
    public $name;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->name === null){
            $this->name = 'World';
        }
    }

    public function run()
    {
        return "Hello, {$this->name} !";
    }
}